### ISSUE TITLE
Opening up streamseek 

### ISSUE THREAD

**Issue by inmicro** [andreabertagnolli/streamseek#7]
So I stumbled across your project. It is really cool, but I was wondering whether you could use it to create a discord music bot. Can you give me tips on how I can use your streamseek for a backend? Thanks

**Comment by ndr-brt** [comment]
Streamseek was a frontend, for the backend I used (and partecipated to) https://github.com/f-hj/slsk-client, but unfortunately some my PRs remained appended there a lot of months so I get tired and I abandoned everything, but yes, I think it can be used to create a discord music bot
